apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: k6-performance-tests
spec:
  metrics:
  - name: k6-performance-tests
    provider:
        job:
          metadata:
            name: k6-performance-tests
          spec:
            template:
              spec:
                containers:
                - name: k6-performance-tests
                  image: grafana/k6:master 
                  command: ["k6", "run", "-o", "experimental-prometheus-rw", "/home/k6/script.js"]
                  envFrom:
                    - configMapRef:
                        name: k6-performance-tests
                  volumeMounts:
                    - mountPath: /home/k6
                      name: k6-performance-test-script
                restartPolicy: Never
                volumes:
                - name: k6-performance-test-script
                  configMap:
                    name: k6-performance-test-script
            backoffLimit: 0