apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: progressive-delivery-anaysis
spec:
  metrics:
  - name: progressive-delivery-anaysis
    successCondition: len(result) == 0 || result[0] == 0.0
    provider:
      prometheus:
        address: http://kube-prometheus-stack-prometheus.monitoring.svc.cluster.local:9090
        query: |
            sum(rate(http_server_requests_seconds_count{container="{{ template "hack24-app.name" . }}", service="{{ template "hack24-app.name" . }}-canary-svc", status=~"5.."}[1m]))