apiVersion: v1
kind: Service
metadata:
  name: {{ template "hack24-app.name" . }}-svc
  labels:
    app: {{ template "hack24-app.name" . }}-svc
spec:
  # type: NodePort
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http-app-port
  selector:
    app: {{ template "hack24-app.name" . }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "hack24-app.name" . }}-canary-svc
  labels:
    app: {{ template "hack24-app.name" . }}-canary-svc
spec:
  # type: NodePort
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http-app-port
  selector:
    app: {{ template "hack24-app.name" . }}