name: Build insight-ops hack24 demo app

on:
  push:
    branches:
      - v*
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - id: export-chart-id
        name: Export Chart ID
        run: |
          echo "CHART_ID=${GITHUB_REF#refs/heads/}" >> $GITHUB_OUTPUT

      - id: setup-maven
        name: Setup Maven Action
        uses: s4u/setup-maven-action@v1.9.0
        with:
          java-version: 21
          maven-version: 3.8.8

      - name: Build App using Maven
        run: |
          mvn clean install

      - id: setup-gcloud-auth
        name: Setup Auth with Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - id: setup-gcr-docker-config
        name: Setup Docker Config for GCR
        run: gcloud auth configure-docker

      - id: build-docker-image
        name: Build Docker Image
        run: |
          docker build --platform linux/amd64 -t hack24-app:${GITHUB_REF#refs/heads/} .

      - id: package-helm-charts
        name: Package Helm Charts
        run: |
          helm package helm/hack24-app --version ${GITHUB_REF#refs/heads/}

      - id: setup-helm-repo-and-push-helm-chart
        name: Setup Helm Repo and Push Helm Chart
        env:
          GCLOUD_SERVICE_ACCOUNT_KEY: ${{ secrets.GCP_SA_KEY }}
          CHART_NAME: hack24-app
          CHART_ID: ${{ steps.export-chart-id.outputs.CHART_ID }}
          CHART_PATH: helm/hack24-app
        run: |
          #Install Helm
          HELM_VERSION=3.1.1
          HELM_GCS_VERSION=0.4.1
          
          echo "Installing Helm..."
          wget -q https://get.helm.sh/helm-v${HELM_VERSION}-linux-amd64.tar.gz
          tar -zxf helm-v${HELM_VERSION}-linux-amd64.tar.gz
          sudo mv linux-amd64/helm /usr/local/bin/helm
          helm version
          
          #Install Helm GCS Plugin
          echo "Installing helm-gcs plugin..."
          helm plugin install https://github.com/hayorov/helm-gcs --version ${HELM_GCS_VERSION}
          
          #Setup helm repo
          GCS_BUCKET_NAME="gs://helm-chart-repo"
          echo "${GCLOUD_SERVICE_ACCOUNT_KEY}" > svc-acc.json
          export GOOGLE_APPLICATION_CREDENTIALS=svc-acc.json
          
          helm gcs init ${GCS_BUCKET_NAME}
          
          echo "Adding gcs bucket repo ${GCS_BUCKET_NAME}"
          helm repo add helm-repo ${GCS_BUCKET_NAME}
          
          helm repo update
          helm lint $CHART_PATH/.
          echo "helm gcs push $CHART_NAME-$CHART_ID.tgz helm-repo --force --retry"
          helm gcs push $CHART_NAME-$CHART_ID.tgz helm-repo --force --retry

      - id: push-docker-image
        name: Push Docker Image to GCR
        run: |
          docker push hack24-app:${GITHUB_REF#refs/heads/}
